/* CRYPTOCOMPARE */
export const CC_COINLIST_BEGIN = "CC_COINLIST_BEGIN";
export const CC_COINLIST_SUCCESS = "CC_COINLIST_SUCCESS";
export const CC_COINLIST_FAIL = "CC_COINLIST_FAIL";

export const CC_GETPRICE_BEGIN = "CC_GETPRICE_BEGIN";
export const CC_GETPRICE_SUCCESS = "CC_GETPRICE_SUCCESS";
export const CC_GETPRICE_FAIL = "CC_GETPRICE_FAIL";
/* CRYPTOCOMPARE */